### ISSUE TITLE
实验精度

### ISSUE THREAD

**Issue by Jocelyn886** [TROUBADOUR000/AMD#2]
以ETTH1数据集为例，我设置了预测长度96，输入长度{96, 192, 336, 512, 672, 720}都进行了实验，但是预测效果比您论文中的结果要差很多。

**Comment by TROUBADOUR000** [comment]
现在的代码仍有部分bug，最近会进行重构。
对于您的问题，tsAMD.py的AMD类最后进行了两个'denorm'操作导致最后结果出错，请去掉最后一次，即删去以下部分：
` # x, moe_loss = self.model(x)
   if self.norm:
       x = self.rev_norm(x, 'denorm', self.target_slice)`
我们会尽快更新完善的代码。
