### ISSUE TITLE
bug修复建议

### ISSUE THREAD

**Issue by Jocelyn886** [TROUBADOUR000/AMD#3]
当单变量预测单变量时，会报错。
将common.py的第133和136行末尾加.clone()即可
    output[:, :, :self.n_history * self.patch] = x[:, :, :self.n_history * self.patch].clone()
        for i in range(self.n_history * self.patch, self.input_shape[0], self.patch):
            # input [batch_size, feature_num, self.n_history * patch]
            input = output[:, :, i - self.n_history * self.patch: i].clone()

**Comment by TROUBADOUR000** [comment]
非常感谢您的宝贵建议，我们会尽快进行修改。近期我们将对代码进行重构和优化，届时恭请您继续提供宝贵意见。
