### ISSUE TITLE
Is the output of MDM used as input for DDI ?

### ISSUE THREAD

**Issue by CatchMyCats** [TROUBADOUR000/AMD#4]
According to the code, the output of MDM is time_embedding and it is used in moe. The input of DDI blocks is the original input x.
In the paper, MDM's output is used as input of DDI.
I am not sure whether the output of MDM is used only in moe, or it should be used as input of DDI too. 
Maybe I made some mistakes, please help me.

The related code is: (in tsAMS.py)
# layer norm
if self.norm:
    x = self.rev_norm(x, 'norm')
# [batch_size, seq_len, feature_num]

# [batch_size, seq_len, feature_num]
x = torch.transpose(x, 1, 2)
# [batch_size, feature_num, seq_len]

time_embedding = self.pastmixing(x)

for fc_block in self.fc_blocks:
    x = fc_block(x)

# MOE
x, moe_loss = self.moe(x, time_embedding)  # seq_len -> pred_len

**Comment by TROUBADOUR000** [comment]
Thanks for your attention to our work. After conducting experiments, we found that the prediction performance improves when the input of DDI blocks is changed to the output of MDM. We will update the code and results as soon as possible.
